#ifndef WINDOWSINTERGATION_GLOBAL_H
#define WINDOWSINTERGATION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(WINDOWSINTEGRATION_LIBRARY)
#  define WINDOWSINTERGATIONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define WINDOWSINTERGATIONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // WINDOWSINTERGATION_GLOBAL_H
